import Link from "next/link";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Regular, Medium, SemiBold, Bold
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-900 text-white p-4 space-y-4">
            <h2 className="text-xl font-bold">YourApp</h2>
            <nav className="mt-4 space-y-2">
              <Link href="/">🏠 Home</Link><br />
              <Link href="/posting">📄 Posting</Link>
            </nav>
          </aside>

          {/* Main content (acts like <Outlet/>) */}
          <main className="flex-1 p-6 bg-gray-100">{children}</main>
        </div>
      </body>
    </html>
  );
}
